name: Create and publish a Docker image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Safe debug: confirms secrets are present without printing the token
      - name: Debug Docker Hub creds (safe)
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "dockerhub_username=${DOCKER_HUB_USERNAME}"
          echo "dockerhub_token_length=${#DOCKER_HUB_PASSWORD}"
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Login only when secrets are expected to be available (push/manual), not for PRs
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build on PR (no push)
      - name: Build (no push) for PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false
          tags: eugene8pro/eupoetry:pr

      # Build + push on push/manual
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            eugene8pro/eupoetry:2.0
            eugene8pro/eupoetry:latest

      - name: Show image digest
        if: github.event_name != 'pull_request'
        run: echo "${{ steps.docker_build.outputs.digest }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-docker]
    # Deploy only on push to main (not on PR, not on manual unless you want it)
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /opt/apps/eu_poetry_website/eu_website_deploy/
            docker compose --env-file .env -f docker-compose.prod.yaml down
            docker compose --env-file .env -f docker-compose.prod.yaml pull
            docker compose --env-file .env -f docker-compose.prod.yaml up -d
            docker image prune -f
