"""
Django settings for eu_website_project project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

if os.environ.get("DEBUG") == "True":
    print("DEBUG", os.environ.get("DEBUG"))
    SECRET_KEY = '12345678'
    print('SECRET_KEY:', SECRET_KEY)
    DEBUG = True
    print("DEBUG =", DEBUG)
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")
    print("ALLOWED_HOSTS:", ALLOWED_HOSTS)
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(",")
    print("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS)

elif os.environ.get("DEBUG") == "False":
    print("DEBUG = ", os.environ.get("DEBUG"))
    SECRET_KEY = os.getenv("SECRET_KEY")
    DEBUG = False
    print("DEBUG:", DEBUG)
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")
    print("ALLOWED_HOSTS:", ALLOWED_HOSTS)
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(",")
    print("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS)
else:
    print("ENV not set to development or production, you launch dockerized app")
    ALLOWED_HOSTS = ['0.0.0.0', 'http//0.0.0.0', 'http//0.0.0.0:8008', '0.0.0.0:8008',
                     'http://eupoetry.kyiv.ua.local', 'http://eupoetry.kyiv.ua.local:88',
                     'eupoetry.kyiv.ua.local', 'http://eupoetry.kyiv.ua.local:88/admin',
                     'eupoetry.kyiv.ua.local:88/admin', 'http://eupoetry.kyiv.ua', 'eupoetry.kyiv.ua']
    SECRET_KEY = '12345678'
    print('SECRET_KEY:', SECRET_KEY)
    DEBUG = True
    print("DEBUG:", DEBUG)
    CSRF_TRUSTED_ORIGINS = ALLOWED_HOSTS
    print("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS)


# Application definition

INSTALLED_APPS = [
    "eupoetry.apps.EupoetryConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "eu_website_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "eu_website_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db" / "verses.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False

# CSRF_TRUSTED_ORIGINS = ALLOWED_HOSTS

APPEND_SLASH = True
