# Generated by Django 4.1.2 on 2022-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eupoetry", "0002_eupro_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawverses",
            name="html_name",
            field=models.CharField(default="any_name", max_length=50),
            preserve_default=False,
        ),
    ]
