# Generated by Django 4.1.2 on 2022-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eupoetry", "0003_rawverses_html_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eupro",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rawverses",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
