# Generated by Django 4.1.13 on 2023-12-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eupoetry', '0004_alter_eupro_id_alter_rawverses_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eupro',
            name='date_of_writing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eupro',
            name='html_name',
            field=models.CharField(default='eupro', max_length=50),
        ),
    ]
