# Generated by Django 4.1.13 on 2023-12-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eupoetry', '0005_eupro_date_of_writing_eupro_html_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eupro',
            old_name='fact',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='rawverses',
            old_name='verses',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='eupro',
            name='html_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Hermeneutics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(max_length=65535)),
                ('date_of_writing', models.DateField(blank=True, null=True)),
                ('raw_verses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eupoetry.rawverses')),
            ],
            options={
                'db_table': 'hermeneutics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('date_of_writing', models.DateField(blank=True, null=True)),
                ('raw_verses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eupoetry.rawverses')),
            ],
            options={
                'db_table': 'audio',
                'managed': True,
            },
        ),
    ]
