# Generated by Django 4.1.2 on 2022-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawVerses",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_of_writing", models.DateField(blank=True, null=True)),
                ("title", models.TextField(null=True)),
                ("verses", models.TextField(max_length=50000, null=True)),
            ],
            options={
                "db_table": "raw_verses",
                "managed": True,
            },
        ),
    ]
