# Generated by Django 4.1.2 on 2022-10-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawVerses",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("date_of_writing", models.DateField(blank=True, null=True)),
                ("title", models.TextField(null=True)),
                ("verses", models.TextField(max_length=50000, null=True)),
            ],
            options={
                "db_table": "raw_verses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IdJsonWords",
            fields=[
                (
                    "id_json",
                    models.OneToOneField(
                        db_column="id_json",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="eupoetry.rawverses",
                    ),
                ),
                ("words", models.TextField(max_length=50000)),
            ],
            options={
                "db_table": "id_json_words",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IdWord",
            fields=[
                (
                    "id_word",
                    models.OneToOneField(
                        db_column="id_word",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="eupoetry.rawverses",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "id_word",
                "managed": False,
            },
        ),
    ]
