# Generated by Django 4.1.2 on 2022-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eupoetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eupro",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
