version: '3.7'
services:
  django_gunicorn:
    image: eugene8pro/eupoetry:1.0
    env_file:
      - ./.env
    environment:
      - ENV=production 
    volumes: 
      - static_volume:/home/eugene/static/
      - db_volume:/home/eugene/db/
    ports:
      - "8008:8008"

  nginx:
    build:
      context: ./nginx_prod
    env_file:
      - ./.env # .env file is in .gitignore, it should be manually set in the same directory as docker-compose.yaml
    environment:
      - ENV=production 
    volumes: 
      - static_volume:/home/eugene/static/
    ports:
      - "88:88"
    depends_on:
      - django_gunicorn

volumes:
  static_volume:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
